useless_number_game/views/home.py
"""
Routes and views for the flask application.
"""

import flask, datetime
from flask import Flask, Config, Blueprint, render_template, url_for, request, session, redirect
from useless_number_game import app

blueprint = Blueprint('home', __name__)


@blueprint.route('/')
def home():
	return render_template('home.html', title_ext='')


@blueprint.route('/coming-soon')
@blueprint.route('/coming-soon/')
def coming_soon():
	return render_template('comingsoon.html', title_ext='Coming Soon – ')

useless_number_game/views/useless_offshore_binary_tree.py
"""
Routes and views for the flask application.
"""

import flask, ssl, datetime
from flask import Flask, Config, Blueprint, render_template, url_for, request, session, redirect
from flask_pymongo import PyMongo
from werkzeug.security import generate_password_hash, check_password_hash
from useless_number_game import app

blueprint = Blueprint('useless_offshore_binary_tree', __name__, url_prefix='/uselessoffshorebinarytree')

cluster_username = 'admin'
cluster_password = 'admin'
cluster_dbname = 'useless-offshore-binary-tree'

app.config['MONGO_DBNAME'] = cluster_dbname
app.config['MONGO_URI'] = 'mongodb+srv://{}:{}@useless-number-game.idxzf.azure.mongodb.net/{}?retryWrites=false&w=majority'.format(
	cluster_username,
	cluster_password,
	cluster_dbname
)

nodes = PyMongo(app, ssl=True, ssl_cert_reqs=ssl.CERT_NONE).db.nodes


def is_node_full(node):
	return node['left'] != '' and node['right'] != ''


@blueprint.route('/')
def home():
	return render_template('useless_offshore_binary_tree/home.html', title_ext='')


@blueprint.route('/tree/navigate/<key>')
@blueprint.route('/tree/navigate/<key>/')
# Pre: All values of key exist within the tree
def tree_navigate(key):
	node = nodes.find_one({'key': key})
	child_left = nodes.find_one({'key': node['left']})
	child_right = nodes.find_one({'key': node['right']})
	return render_template(
		'useless_offshore_binary_tree/tree_navigate.html',
		title_ext='Navigate {} – '.format(node['key']),
		node=node,
		child_left=child_left,
		child_right=child_right
	)


@blueprint.route('/tree/add', methods=['GET', 'POST'])
@blueprint.route('/tree/add/', methods=['GET', 'POST'])
def tree_add():
	error = None

	if request.method == 'POST':
		new_node_exists = nodes.find_one({'key': request.form['key']})
		parent = nodes.find_one({'key': request.form['parent']})

		if new_node_exists:
			error = 'A node with that name already exists. Sorry.'
		elif request.form['key'] == '' or request.form['item'] == '' or request.form['parent'] == '':
			error = 'Dude, fill in the goddamn form, come on…'
		elif parent is None:
			error = 'That parent node does not exist. Oops!'
		elif is_node_full(parent):
			error = 'That parent node is already full!'
		else:
			author = session['username'] if 'username' in session else 'Unknown'
			new_node = {
				'key': request.form['key'],
				'author': author,
				'dateAdded': str(datetime.datetime.now().strftime("%Y-%m-%d")),
				'item': request.form['item'],
				'left': '',
				'right': ''
			}

			if parent['left'] == '':
				nodes.update(
					{'key': request.form['parent']},
					{'$set': {'left': request.form['key']}}
				)
			else:
				nodes.update(
					{'key': request.form['parent']},
					{'$set': {'right': request.form['key']}}
				)
			nodes.insert(new_node)
			# TODO: Clear form after submission
	return render_template(
		'useless_offshore_binary_tree/tree_add.html',
		title_ext='Add a Node – ',
		error=error
	)


@blueprint.route('/about')
@blueprint.route('/about/')
def about():
	return render_template(
		'useless_offshore_binary_tree/about.html',
		title_ext='About – '
	)

useless_number_game/templates/useless_offshore_binary_tree/about.html
{% extends "useless_offshore_binary_tree/layout.html" %}

{% block content %}

<h1 align="center">Useless Offshore Binary Tree</h1>

<div class="section" style="text-align: left">
    <p1>
        If you know computer science, then you know what a binary tree is. If you don't, then this is probably not a page for you. Get lost.
        The particular binary tree you see on this site has been stored on a remote MongoDB database somewhere in… Ireland, I'm guessing?
        We've then given you a way to navigate through this tree, as well as add new nodes onto it.
        This is just a stupid practice on data structures. Ignore me.
        <br />
        For more information, view the <a href="https://github.com/jyjulianwong/exercise-useless-number-game" target="_blank">GitHub repository</a>
        for this website to see how it was made.
    </p1>
</div>

<div class="section">
    <button type="button" class="buttonNav" onclick="window.location.href='{{ url_for('.home') }}'">Back…</button>
</div>

{% endblock %}

useless_number_game/templates/useless_offshore_binary_tree/home.html
{% extends "useless_offshore_binary_tree/layout.html" %}

{% block content %}

<div class="section">
    <h1>Useless Offshore Binary Tree</h1>
</div>

<div class="section">
    <button type="button" class="buttonNav" onclick="window.location.href='{{ url_for('home.coming_soon') }}'">See the tree</button>
    <button type="button" class="buttonNav" onclick="window.location.href='{{ url_for('.tree_navigate', key='root') }}'">Navigate the tree</button>
    <button type="button" class="buttonNav" onclick="window.location.href='{{ url_for('.tree_add') }}'">Add to the tree</button>
    <button type="button" class="buttonNav" onclick="window.location.href='{{ url_for('.about') }}'">Wtf is this?</button>
</div>

{% endblock %}

useless_number_game/templates/useless_offshore_binary_tree/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title_ext }}Useless Offshore Binary Tree</title>
    <link rel="stylesheet" type="text/css" href="/static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/content/uselessoffshorebinarytree.css" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto+Mono">
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
</head>

<body>
    <div class="bg bg_jamesmay">
        {% block content %}{% endblock %}
        <script src="/static/scripts/jquery-1.10.2.js"></script>
        <script src="/static/scripts/bootstrap.js"></script>
        <script src="/static/scripts/respond.js"></script>
        {% block scripts %}{% endblock %}
    </div>
</body>
</html>

useless_number_game/templates/useless_offshore_binary_tree/tree_add.html
{% extends "useless_offshore_binary_tree/layout.html" %}

{% block content %}

<div class="section">
    <h2>Add a new node…</h2>
    <br />
    <form action="{{ url_for('.tree_add') }}" method="post">
        <input type="text" placeholder="Name of the node?" name="key" value="{{ request.form['key'] }}">
        <br />
        <input type="text" placeholder="Description of the node?" name="item" value="{{ request.form['item'] }}">
        <br />
        <input type="text" placeholder="Name of this node's parent node?" name="parent" value="{{ request.form['parent'] }}">
        <br />

        {% if error %}

        <p2><err>{{ error }}</err></p2>

        {% endif %}

        <div class="section">
            <input type="submit" class="buttonNav" value="Add…">
        </div>
    </form>
</div>

<div class="section">
    <button type="button" class="buttonNav" onclick="window.location.href='{{ url_for('.home') }}'">Back…</button>
</div>

{% endblock %}

useless_number_game/templates/useless_offshore_binary_tree/tree_navigate.html
{% extends "useless_offshore_binary_tree/layout.html" %}

{% block content %}

<div class="section">
    <h2>Navigate the tree…</h2>
</div>

<div class="section">
    <div class="node">
        <p1>Name: {{ node['key'] }}<br />Description: {{ node['item'] }}<br /></p1>
        <div class="section">
            <p2>Created by: {{ node['author'] }}<br />Created on: {{ node['dateAdded'] }}<br /></p2>
        </div>
    </div>

    <div class="section" style="display: flex; justify-content: center;">

        {% if child_left %}

        <div class="node nodeChild">
            <p1>Name: <a href="{{ url_for('.tree_navigate', key=child_left['key']) }}">{{ child_left['key'] }}</a></p1>
        </div>

        {% endif %}

        {% if child_right %}

        <div class="node nodeChild">
            <p1>Name: <a href="{{ url_for('.tree_navigate', key=child_right['key']) }}">{{ child_right['key'] }}</a></p1>
        </div>

        {% endif %}

    </div>
</div>

{% endblock %}