useless_number_game/views/home.py
"""
Routes and views for the flask application.
"""

import flask, datetime
from flask import Flask, Config, Blueprint, render_template, url_for, request, session, redirect
from useless_number_game import app

blueprint = Blueprint('home', __name__)


@blueprint.route('/')
def home():
	return render_template('home.html', title_ext='')


@blueprint.route('/coming-soon')
@blueprint.route('/coming-soon/')
def coming_soon():
	return render_template('comingsoon.html', title_ext='Coming Soon – ')

useless_number_game/views/useless_meme_1.py
"""
Routes and views for the flask application.
"""

import flask
from flask import Flask, Config, Blueprint, render_template, url_for, request, session, redirect
from useless_number_game import app

blueprint = Blueprint('useless_meme_1', __name__, url_prefix='/uselessmeme1')


@blueprint.route('/')
def main():
	return render_template('useless_meme_1/main.html')

useless_number_game/views/useless_meme_2.py
"""
Routes and views for the flask application.
"""

import flask
from flask import Flask, Config, Blueprint, render_template, url_for, request, session, redirect
from useless_number_game import app

blueprint = Blueprint('useless_meme_2', __name__, url_prefix='/uselessmeme2')


@blueprint.route('/')
def main():
	return render_template('useless_meme_2/main.html')

useless_number_game/views/useless_number_game.py
"""
Routes and views for the flask application.
"""

import flask, ssl, datetime
from flask import Flask, Config, Blueprint, render_template, url_for, request, session, redirect
from flask_pymongo import PyMongo
from werkzeug.security import generate_password_hash, check_password_hash
from useless_number_game import app

blueprint = Blueprint('useless_number_game', __name__, url_prefix='/uselessnumbergame')

cluster_username = 'admin'
cluster_password = 'admin'
cluster_dbname = 'useless-number-game'

app.config['MONGO_DBNAME'] = cluster_dbname
app.config['MONGO_URI'] = 'mongodb+srv://{}:{}@useless-number-game.idxzf.azure.mongodb.net/{}?retryWrites=false&w=majority'.format(
	cluster_username,
	cluster_password,
	cluster_dbname
)

players = PyMongo(app, ssl=True, ssl_cert_reqs=ssl.CERT_NONE).db.players


def get_player_status():
	return ('Welcome, ' + session['username'] + '!') if ('username' in session) else 'Oh, hi loser! Want to sign in?'


@blueprint.route('/')
def home():
	return render_template(
		'useless_number_game/home.html',
		title_ext='',
		player_status=get_player_status()
	)


@blueprint.route('/sign-up', methods=['GET', 'POST'])
@blueprint.route('/sign-up/', methods=['GET', 'POST'])
def sign_up():
	error = None
	is_username_inval = False
	inval_chars = ['`', '~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '=', '+', '[', '{', ']', '}', '|', ';',
				   ':', '"', ',', '<', '>', '/', '?', ' ']
	if request.method == 'POST':
		player = players.find_one({'username': request.form['username']})
		for n in inval_chars:
			is_username_inval = not is_username_inval and (n in request.form['username'])
		if player:
			error = "Someone's taken that username. Sorry."
		elif request.form['username'] == '':
			error = 'Actually enter a username, please…'
		elif request.form['password'] == '':
			error = 'Actually enter a password, please…'
		elif (request.form['passwordConfirm'] == '') or (request.form['passwordConfirm'] != request.form['password']):
			error = "Your passwords aren't the same. Try again…"
		elif is_username_inval:
			error = "You can't put special symbols or spaces in your username. Try again…"
		else:
			sign_up_date = datetime.datetime.now()
			players.insert(
				{
					'username': request.form['username'],
					'password': generate_password_hash(request.form['password']),
					'signUpDate': str(sign_up_date.strftime("%Y-%m-%d"))
				}
			)
			session['username'] = request.form['username']
			return redirect(url_for('.home'))
	return render_template(
		'useless_number_game/signup.html',
		title_ext='Sign Up – ',
		error=error
	)


@blueprint.route('/sign-in', methods=['GET', 'POST'])
@blueprint.route('/sign-in/', methods=['GET', 'POST'])
def sign_in():
	error = None
	if request.method == 'POST':
		player = players.find_one({'username': request.form['username']})
		if player:
			if check_password_hash(player['password'], request.form['password']):
				session['username'] = request.form['username']
				return redirect(url_for('.home'))
			else:
				error = "You've got the wrong username or password, mate."
		else:
			error = "You've got the wrong username, mate."
	return render_template(
		'useless_number_game/signin.html',
		title_ext='Sign In – ',
		error=error
	)


@blueprint.route('/sign-out')
@blueprint.route('/sign-out/')
def sign_out():
	session.clear()
	return render_template('useless_number_game/signout.html', title_ext='Sign Out – ')


@blueprint.route('/main')
@blueprint.route('/main/')
def main():
	return render_template(
		'useless_number_game/main.html',
		title_ext='',
		player_status=get_player_status()
	)


@blueprint.route('/player-error')
@blueprint.route('/player-error/')
def player_error():
	return render_template('useless_number_game/playererror.html', title_ext='')


@blueprint.route('/player/<username>')
@blueprint.route('/player/<username>/')
def player_profile(username):
	player = players.find_one({'username': username})
	if player:
		username = player['username']
		sign_up_date = player['signUpDate']
		return render_template(
			'useless_number_game/player_profile.html',
			title_ext='{} – '.format(username),
			username=username,
			player_status=get_player_status(),
			sign_up_date=sign_up_date
		)
	return redirect(url_for('.player_error'))


@blueprint.route('/player/<username>/change-password', methods=['GET', 'POST'])
@blueprint.route('/player/<username>/change-password/', methods=['GET', 'POST'])
def player_change_password(username):
	if session['username'] != username:
		return redirect(url_for('.home'))

	error = None

	if request.method == 'POST':
		player = players.find_one({'username': username})
		if request.form['oldPassword'] == "" or request.form['newPassword'] == "" or request.form['newPasswordConfirm'] == "":
			error = "Actually enter a password, please..."
		elif check_password_hash(player['password'], request.form['oldPassword']):
			if request.form['newPassword'] == request.form['newPasswordConfirm']:
				players.update(
					{'username': session['username']},
					{'$set': {'password': generate_password_hash(request.form['newPassword'])}}
				)
				return redirect(url_for('.player_change_password_confirm', username=username))
			else:
				error = "Your passwords aren't the same. Try again…"
		else:
			error = "You've got the wrong password, mate. Try again…"
	return render_template(
		'useless_number_game/player_changepassword.html',
		title_ext='Change {}\'s Password – '.format(username),
		error=error,
		username=username
	)


@blueprint.route('/player/<username>/change-password/confirm')
@blueprint.route('/player/<username>/change-password/confirm/')
def player_change_password_confirm(username):
	return render_template(
		'useless_number_game/player_changepassword_confirm.html',
		title_ext=''
	)


@blueprint.route('/player/<username>/delete', methods=['GET', 'POST'])
@blueprint.route('/player/<username>/delete/', methods=['GET', 'POST'])
def player_delete(username):
	if request.method == 'POST':
		if session['username'] == username:
			players.remove({'username': username})
			session.clear()
		return redirect(url_for('.home'))
	return render_template('useless_number_game/player_delete.html', title_ext='Delete a Player – ')


@blueprint.route('/about')
@blueprint.route('/about/')
def about():
	return render_template(
		'useless_number_game/about.html',
		title_ext='About – ',
		player_status=get_player_status()
	)

useless_number_game/views/useless_offshore_binary_tree.py
"""
Routes and views for the flask application.
"""

import flask, ssl, datetime
from flask import Flask, Config, Blueprint, render_template, url_for, request, session, redirect
from flask_pymongo import PyMongo
from werkzeug.security import generate_password_hash, check_password_hash
from useless_number_game import app

blueprint = Blueprint('useless_offshore_binary_tree', __name__, url_prefix='/uselessoffshorebinarytree')

cluster_username = 'admin'
cluster_password = 'admin'
cluster_dbname = 'useless-offshore-binary-tree'

app.config['MONGO_DBNAME'] = cluster_dbname
app.config['MONGO_URI'] = 'mongodb+srv://{}:{}@useless-number-game.idxzf.azure.mongodb.net/{}?retryWrites=false&w=majority'.format(
	cluster_username,
	cluster_password,
	cluster_dbname
)

nodes = PyMongo(app, ssl=True, ssl_cert_reqs=ssl.CERT_NONE).db.nodes


def is_node_full(node):
	return node['left'] != '' and node['right'] != ''


@blueprint.route('/')
def home():
	return render_template('useless_offshore_binary_tree/home.html', title_ext='')


@blueprint.route('/tree/navigate/<key>')
@blueprint.route('/tree/navigate/<key>/')
# Pre: All values of key exist within the tree
def tree_navigate(key):
	node = nodes.find_one({'key': key})
	child_left = nodes.find_one({'key': node['left']})
	child_right = nodes.find_one({'key': node['right']})
	return render_template(
		'useless_offshore_binary_tree/tree_navigate.html',
		title_ext='Navigate {} – '.format(node['key']),
		node=node,
		child_left=child_left,
		child_right=child_right
	)


@blueprint.route('/tree/add', methods=['GET', 'POST'])
@blueprint.route('/tree/add/', methods=['GET', 'POST'])
def tree_add():
	error = None

	if request.method == 'POST':
		new_node_exists = nodes.find_one({'key': request.form['key']})
		parent = nodes.find_one({'key': request.form['parent']})

		if new_node_exists:
			error = 'A node with that name already exists. Sorry.'
		elif request.form['key'] == '' or request.form['item'] == '' or request.form['parent'] == '':
			error = 'Dude, fill in the goddamn form, come on…'
		elif parent is None:
			error = 'That parent node does not exist. Oops!'
		elif is_node_full(parent):
			error = 'That parent node is already full!'
		else:
			author = session['username'] if 'username' in session else 'Unknown'
			new_node = {
				'key': request.form['key'],
				'author': author,
				'dateAdded': str(datetime.datetime.now().strftime("%Y-%m-%d")),
				'item': request.form['item'],
				'left': '',
				'right': ''
			}

			if parent['left'] == '':
				nodes.update(
					{'key': request.form['parent']},
					{'$set': {'left': request.form['key']}}
				)
			else:
				nodes.update(
					{'key': request.form['parent']},
					{'$set': {'right': request.form['key']}}
				)
			nodes.insert(new_node)
			# TODO: Clear form after submission
	return render_template(
		'useless_offshore_binary_tree/tree_add.html',
		title_ext='Add a Node – ',
		error=error
	)


@blueprint.route('/about')
@blueprint.route('/about/')
def about():
	return render_template(
		'useless_offshore_binary_tree/about.html',
		title_ext='About – '
	)

useless_number_game/templates/comingsoon.html
{% extends "layout.html" %}

{% block content %}

<div class="section">
    <h1>Hold on!</h1>
    <p>We're still working on this bit! Coming soon…</p>
</div>

<div class="section">
    <button type="button" class="buttonNav" onclick="window.location.href='{{ url_for('.home') }}'">Back…</button>
</div>

{% endblock %}

useless_number_game/templates/home.html
{% extends "layout.html" %}

{% block content %}

<div class="section">
    <button
            type="button"
            class="buttonSitePreview"
            onclick="window.location.href='{{ url_for('.coming_soon') }}'">
        Useless Blog
    </button>
    <button
            type="button"
            class="buttonSitePreview"
            onclick="window.location.href='{{ url_for('useless_meme_1.main') }}'">
        Useless Meme 1
    </button>
    <button
            type="button"
            class="buttonSitePreview"
            onclick="window.location.href='{{ url_for('useless_meme_2.main') }}'">
        Useless Meme 2
    </button>
    <button
            type="button"
            class="buttonSitePreview"
            onclick="window.location.href='{{ url_for('useless_number_game.home') }}'">
        Useless Number Game
    </button>
    <button
            type="button"
            class="buttonSitePreview"
            onclick="window.location.href='{{ url_for('useless_offshore_binary_tree.home') }}'">
        Useless Offshore Binary Tree
    </button>
</div>

<div class="section">
    <p>
        Originally made, with literally zero love and care,
        by <a href="https://github.com/jyjulianwong/" target="_blank">a total crackhead</a> in 2018.
    </p>
</div>

<div class="section">
    <p>
        If anyone has a plan how to turn this website into some sort of T-shirt or merchandise, please contact me,
        because I swear the world seriously needs more pointless ways to let people spend money right now.
    </p>
</div>

{% endblock %}

useless_number_game/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title_ext }}WEBTIU.com</title>
    <link rel="stylesheet" type="text/css" href="/static/content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/content/home.css" />
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Indie+Flower">
    <script src="/static/scripts/modernizr-2.6.2.js"></script>
</head>

<body>
    <div class="bg">
        <div class="section">
            <p>Why even bother? This is…</p>
            <h1 style="line-height: 35%;">USELESS</h1>
            <p>.com</p>
        </div>

        {% block content %}{% endblock %}
        <script src="/static/scripts/jquery-1.10.2.js"></script>
        <script src="/static/scripts/bootstrap.js"></script>
        <script src="/static/scripts/respond.js"></script>
        {% block scripts %}{% endblock %}
    </div>
</body>
</html>

useless_number_game/templates/main.html
{% extends "layout_app.html" %}

{% block app_content %}

<h6 id="score" align="center"></h6>
<h6 id="timer" align="center"></h6>
<h1 id="question" align="center"></h1>

<div style="text-align: center; margin-top: 50px;">
    <button type="button" id="btnAnswerA" class="buttonNav buttonRed" onclick="answerAClick()">A</button>
    <button type="button" id="btnAnswerB" class="buttonNav buttonGreen" onclick="answerBClick()">B</button>
</div>

<div style="text-align: center">
    <button type="button" id="btnAnswerC" class="buttonNav buttonBlue" onclick="answerCClick()">C</button>
    <button type="button" id="btnAnswerD" class="buttonNav buttonYellow" onclick="answerDClick()">D</button>
</div>

<div id="divStart" style="text-align: center; margin-top: 50px;">
    <button type="button" id="btnStart" class="buttonNav" onclick="start()">I am really bored…</button>
</div>

<div id="divMainBack" style="text-align: center">
    <button type="button" id="btnMainBack" class="buttonNav" onclick="window.location.href='home'">Back…</button>
</div>

<script src="/static/scripts/main.js"></script>

{% endblock %}

useless_number_game/templates/start.html
{% extends "layout.html" %}

{% block content %}

{% if 'username' in session %}

<a href="{{ url_for('profile') }}"><statusBar style="margin-top: 20px; margin-bottom: 25px"><p3> {{ playerStatus }} </p3></statusBar></a>

{% else %}

<a href="{{ url_for('signIn') }}"><statusBar style="margin-top: 20px; margin-bottom: 25px"><p3> {{ playerStatus }} </p3></statusBar></a>

{% endif %}

<h1 align="center"> Useless Number Game. </h1>
<h6 align="center"> It's what it says on the tin. </h6>

<div style="text-align: center; margin-top: 25px;">
    <button type="button" id="btnStart" class="buttonNav" onclick="window.location.href='main'">I am bored.</button>
</div>

<div style="text-align: center; margin-top: 25px;">
    <button type="button" id="btnAbout" class="buttonNav" onclick="window.location.href='about'">What is this?</button>
</div>

{% if 'username' not in session %}

<div style="text-align: center; margin-top: 25px;">
    <button type="button" id="btnStartSignUp" class="buttonNav" onclick="window.location.href='signup'">Sign me up.</button>
</div>

<div style="text-align: center; margin-top: 25px;">
    <button type="button" id="btnStartSignIn" class="buttonNav" onclick="window.location.href='signin'">Sign me in.</button>
</div>

{% endif %}

{% if 'username' in session %}

<div style="text-align: center; margin-top: 25px;">
    <button type="button" id="btnStartSignOut" class="buttonRed" onclick="window.location.href='signout'">Sign me out.</button>
</div>

{% endif %}

<div style="text-align: center; margin-top: 25px;">
    <p2>
        Licensed under the GNU General Public License v3.0. Made by <a href="https://github.com/jyjulianwong/" target="_blank">Julian Wong</a> in 2018.
    </p2>
</div>

{% endblock %}